### ISSUE TITLE
How to test on different videos?

### ISSUE THREAD

**Issue by iamgmujtaba** [verlab/StraightToThePoint_CVPR_2020#1]
Hi There,

Thank you for sharing this code. 
Can you please guide me, how I can test FFMethod on different videos?
As per my understanding, I have to prepare a document with sentences. But I could not understand the process relevant to document preparation. What if those sentences/recipe texts are not available in the video? 

If possible, please share your thought about document preparation.

Many thanks,

**Comment by washingtonsk8** [comment]
Hi,

Unfortunately, at this point of the project, you won't be able to run the fast-forward method without texts associated with it. However, if you know the title of the recipe, you can search for the instructions/directions on websites like [All Recipes](https://www.allrecipes.com/), [WikiHow](https://www.wikihow.com/), or even in a dataset like [Recipe1M+](http://pic2recipe.csail.mit.edu/). You can also find other videos and their recipes on the [WatchNCook](http://www.watchncook.com/) website.

Thank you for sharing your doubts,

**Comment by iamgmujtaba** [comment]
Thank you so much for your explanation.
